spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/hittracker
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      port: 6380